packages:
  - 'packages/*'
allowBuilds:
  '@openapitools/openapi-generator-cli': true
  '@parcel/watcher': true
  '@swc/core': true
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - open@11.0.4
